@auth=jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJVSUQiOiI2aGlpYVRXRUxuU09rMFhiWGI0MyIsInRva2VuVmVyc2lvbiI6NjExLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzgxNzcyMjcsImV4cCI6MTY3ODE5ODgyN30.ktqIDMYxTwF0BuOi_lhRcpGHGx-e8s3djm4krDS5eJZIIAYw5wWuK3nuVOe4iHwNe3qOo7QU9gappniR7Ta_3H1m5WulTKsgWS8nkz9EAQmBkZLlGzxqYHAW2obgMmFZS90mRanYhoJOpuTQCg3ENjYgHgUNa0sM-qtbWJ717868v0dzFkYWPPM5kvZOSfoLMqqKC1Wbu9G6iqyv4Hl3aHEsVcN7_fEgpdlubIq1dyA7bA0-4n7T1JTVVQqYcR_KsAFOXvNEtFVkJ1Zrc7irybge631B_uAuCGHHg732tqUvBURlRJMiHZQ8F7Wu7YIL_TIgyr3c0nyYHBOqmryA4Q;


###
POST http://localhost:8000/add/admin
content-type: application/json

{
    "username": "admin01",
    "password": "123456789",
    "fullname": "admin",
    "credit": 0
}


###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "admin01",
    "password": "123456789"
}

###
POST http://localhost:8000/auth/logout
Cookie: {{auth}}
Content-Type: application/json

{
    "username": "admin01"
}

###
POST http://localhost:8000/add/lotto
Cookie: {{auth}}
content-type: application/json

{
    "name": "ดาวน์โจนส์ VIP",
    "img_flag": "jonevip.jpg",
    "open": "2023-01-19 06.00",
    "close": "2023-01-19 00.10",
    "report": "2023-01-19 00.30",
    "status": "OPEN"
}

###
DELETE http://localhost:8000/delete/lotto
Cookie: {{auth}}
content-type: application/json

{
    "id": "LKyASx2SgDOtGFioWDT3"
}

###
GET http://localhost:8000/get/lotto/all
Cookie: {{auth}}

###
POST http://localhost:8000/add/agent
Cookie: {{auth}}
content-type: application/json

{
    "username": "agent01",
    "password": "123456789",
    "fullname": "agent",
    "credit": 0
}

###
POST http://localhost:8000/add/member
Cookie: {{auth}}
content-type: application/json

{
    "username": "member1111",
    "password": "123456789",
    "fullname": "member11111111111",
    "credit": 0,
    "store_id": "3RDYTBqOjervu82IKQXm",
    "agent_create_id": "pSJ2jiwWPMj7ksCQG5wV",
    "admin_create_id": "6hiiaTWELnSOk0XbXb43",
    "manager_create_id": "9pxJRIMKeNIRhqJlMDcZ",
    "role": "MEMBER",
    "status": "REGULAR"
}

###
GET http://localhost:8000/get/bill/all
Cookie: {{auth}}

###
GET http://localhost:8000/get/user/me
Cookie: {{auth}}

###
GET http://localhost:8000/get/user/all
Cookie: {{auth}}

###
PUT http://localhost:8000/update/status/agent
Cookie: {{auth}}
content-type: application/json

{
    "id": "85MI669pD37GGckaKAxh",
    "status": "REGULAR"
}