@auth=jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJVSUQiOiJwU0oyaml3V1BNajdrc0NRRzV3ViIsInRva2VuVmVyc2lvbiI6OSwicm9sZSI6IkFHRU5UIiwiaWF0IjoxNjc2NjE3OTU0LCJleHAiOjE2NzY2Mzk1NTR9.Xrw04T_5G6jNo6_hyyv88TbkaoUBxpK3rzuO7-MJDEfJZLwXuMIMxNqHeV-PxTfwSA6sSXXURE-ZZTRqYkQQvBYHwuUBs6RWNxh0cDZpWFUNe-ZNJFTCUZl_l2DE-ZTpm3O8Sm2YBKqj1ey90Ysko7I4Kc1xGwpmkaPWR3EMqOxz2hbCby2C-pdaayLrGYg6Ksv6ZIWpQ9zJPLmBRM8vY9JQKqDTLBbjLkohQqtwlRGVztP2oMW-M6_SErsMAw7LYokHu5jGpZWioSxU3Gl0qh9MWUUpKmsGI7Wmt_JNAEflcNhH4TjxdSsTT2urW8PU4rjcLzbpeU-bMwMdGeWYXQ;

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "agent01",
    "password": "123456789"
}

###
POST http://localhost:8000/auth/logout
Cookie: {{auth}}
Content-Type: application/json

{
    "username": "agent01"
}

###
POST http://localhost:8000/add/store
Cookie: {{auth}}
content-type: application/json

{
    "name": "ร้านดีดี",
    "img_logo": "logo.jpg"
}

###
GET http://localhost:8000/get/store/me
Cookie: {{auth}}

###
GET http://localhost:8000/get/lotto/all
Cookie: {{auth}}

###
POST http://localhost:8000/add/rate
Cookie: {{auth}}
content-type: application/json

{
    "store_id":"3RDYTBqOjervu82IKQXm",
    "lotto_id": "LAsvfoFfN6SnIeT18BzC",
    "one_digits": {
        "top": "3",
        "bottom": "4"
    },
    "two_digits": {
        "top": "95",
        "bottom": "95"
    },
    "three_digits": {
        "top": "800",
        "toad": "125"
    },
    "bet_one_digits": {
        "top": "1:10000:100000",
        "bottom": "1:10000:100000"
    },
    "bet_two_digits": {
        "top": "1:10000:100000",
        "bottom": "1:10000:100000"
    },
    "bet_three_digits": {
        "top": "1:10000:100000",
        "bottom": "1:10000:100000"
    },
    "committion": {
        "one_digits": {
            "top": "1",
            "bottom": "1"
        },
        "two_digits": {
            "top": "1",
            "bottom": "1"
        },
        "three_digits": {
            "top": "3",
            "toad": "3"
        }
    }
}

###
GET http://localhost:8000/get/rate/me/all
Cookie: {{auth}}

###
POST http://localhost:8000/add/manager
Cookie: {{auth}}
content-type: application/json

{
    "store_id": "3RDYTBqOjervu82IKQXm",
    "username": "manager01",
    "password": "123456789",
    "fullname": "manager",
    "credit": 0
}

###
GET http://localhost:8000/get/user/me
Cookie: {{auth}}

###
PUT http://localhost:8000/add/credit
Cookie: {{auth}}
content-type: application/json

{
    "id": "9pxJRIMKeNIRhqJlMDcZ",
    "credit": 50000
}

###
PUT http://localhost:8000/add/credit
Cookie: {{auth}}
content-type: application/json

{
    "id": "9pxJRIMKeNIRhqJlMDcZ",
    "credit": 50000
}


###
PUT http://localhost:8000/remove/credit
Cookie: {{auth}}
content-type: application/json

{
    "id": "FHKdAOjsQz8SCtpArqKJ",
    "credit": 10000
}

###
POST http://localhost:8000/add/member
Cookie: {{auth}}
content-type: application/json

{
    "store_id": "U5D7nSeVqplRp8DQi1EG",
    "username": "test01",
    "password": "123456789",
    "fullname": "test01",
    "credit": 0
}

###
POST http://localhost:8000/add/digitclose
Cookie: {{auth}}
content-type: application/json

{
    "lotto_id": "LAsvfoFfN6SnIeT18BzC",
    "percent": 0,
    "rate_id": "Y8yOYqyioxr2a6fospgU",
    "store_id": "3RDYTBqOjervu82IKQXm",
    "one_digits": {
        "top": [],
        "bottom": []
    },
    "two_digits": {
        "top": ["15", "51"],
        "bottom": ["15", "51"]
    },
    "three_digits": {
        "top": [],
        "bottom": []
    }
}

###
GET http://localhost:8000/get/digitclose/me
Cookie: {{auth}}

###
GET http://localhost:8000/get/digitclose/id/LAsvfoFfN6SnIeT18BzC
Cookie: {{auth}}