@auth=Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJVSUQiOiI5cHhKUklNS2VOSVJocUpsTURjWiIsInRva2VuVmVyc2lvbiI6MSwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE2NzQ2Mzk1NDYsImV4cCI6MTY3NDY2MTE0Nn0.s3DEysljMlziaZ-plx61-56jAGo5K5BASYgI2O1RRfZKR2hqnW_MKM4mWHNBvvH6J8mS_U7alerlG6hS9y9zg2FTIHMCKM3QG0dVFiGM6m2JS_uWX0YVba-lIRMimwCNV4babpaT49dzXQ9xPj0gVXD6RZ7KZgd6ay2EOs8XaRl3sYWCkxCcCcdNeZDeVdokosC5EU63XDCUPlrSOOdpDqM_uXnmIZIAf8-TCmxVbJefNPpEpCxuHIX14_p5sKpcRXv_D4ifHMOu5TVxAvnGqhzS1-2xV5BOe3eE5k06iq7zNQ4gxMyyMQsmH2d2CWiwZtyBFV40njXNkJuLKJJEUA


###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "manager01",
    "password": "123456789"
}

###
POST http://localhost:8000/auth/logout
Cookie: {{auth}}
Content-Type: application/json

{
    "username": "manager01"
}

###
GET http://localhost:8000/me
Cookie: {{auth}}

###
GET http://localhost:8000/get/store/me
Cookie: {{auth}}

###
GET http://localhost:8000/get/user/me
Cookie: {{auth}}

###
POST http://localhost:8000/add/member
Cookie: {{auth}}
content-type: application/json

{
    "store_id": "3RDYTBqOjervu82IKQXm",
    "username": "member01",
    "password": "123456789",
    "fullname": "member01",
    "credit": 0
}

###
PUT http://localhost:8000/add/credit
Cookie: {{auth}}
content-type: application/json

{
    "id": "XoMsRsjVihPb2csxQSYj",
    "credit": 20000
}

###
PUT http://localhost:8000/remove/credit
Cookie: {{auth}}
content-type: application/json

{
    "id": "XoMsRsjVihPb2csxQSYj",
    "credit": 10000
}